import type {Metadata} from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({children, slot}: LayoutProps<'/'>) {
  return (
    <html lang="en">
      <body>
        <h1>Root layout</h1>
        {children}
        {slot}
      </body>
    </html>
  );
}
